### ISSUE TITLE
Could it work with new JK BMS's communication board's RS232 port?

### ISSUE THREAD

**Issue by txubelaxu** [syssi/esphome-jk-bms#408]
This is the new JK BMS: https://www.jkbms.com/product/jk-pb2a16s15p-jk-pb2a16s-15p/

It has a comms board with 5 ports:
- 1 RS485 ((RJ45) to be connected to Inverter
- 1 CAN (RJ45) to be connected to Inverter
- 1 RS232 (RJ11)
- 2 RS485 (RJ45) for paralling other (same) BMS

I have given a try to RS232 port but ESP uses modbus protocol. 

Is any way to use serial protocol instead?

More info about HW:
![image](https://github.com/syssi/esphome-jk-bms/assets/156140720/449edff8-cdf0-4582-8517-16d1e2153b62)
![image](https://github.com/syssi/esphome-jk-bms/assets/156140720/f3b3447f-e400-45b8-96a5-967482d2f674)
![image](https://github.com/syssi/esphome-jk-bms/assets/156140720/ee99e079-1189-4f5a-9ea0-e8c74861197b)
![image](https://github.com/syssi/esphome-jk-bms/assets/156140720/9179eef7-d333-4e16-8f98-9517736ea35f)
![image](https://github.com/syssi/esphome-jk-bms/assets/156140720/2e97def0-e15b-4eae-a572-3fb525e51edf)
![image](https://github.com/syssi/esphome-jk-bms/assets/156140720/685b3af9-7924-4147-b2e2-11d4313cbc34)

**Comment by txubelaxu** [comment]
I have tested with no success. ESP32 (Serial2) connected directly to RS232 RJ11 connector. ESP32 RX pin in a pull-up input config.
I send:
`  byte bytesToSend[] = {0x4E, 0x57, 0x00, 0x13, 0x00, 0x00, 0x00, 0x00,
                        0x06, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                        0x68, 0x00, 0x00, 0x01, 0x29};` and... there is no response at all.
I send:
`  byte bytesToSend[] = {0x4E, 0x57, 0x00, 0x13, 0x00, 0x00, 0x00, 0x00,
                        0x06, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                        0x68, 0x00, 0x00, 0x01, 0x29, 0x13, 0x10};` and... no response at all.

I think it is because JK-BMS UART protocol is fixed to a kind of "GPS INPUT" and it cannot be changed from app:
![image](https://github.com/syssi/esphome-jk-bms/assets/156140720/266514a7-9d68-4b31-a068-73fe5e8a18ff)

If you try to change the setting, BMS responses that the new setting can not be saved.

**Comment by syssi** [comment]
@txubelaxu How many items / protocols are available at the drop-down?

**Comment by ibantxo** [comment]
Hi syssi,

There are 3 lines in the settings menu item (status/**settings**/control) regarding to protocols:
![image](https://github.com/syssi/esphome-jk-bms/assets/5004479/c0e56076-0844-42c4-adbb-3768b73e3377)
UART1 and CAN have "OK" button. UART2 has not. Anyway, "OK" button of UART1 does not work with all values, so any selection cannot be saved at this firmware/app version.

UART1 Protocol No.: has the next list inside:
![image](https://github.com/syssi/esphome-jk-bms/assets/5004479/bd0baa53-8140-451a-82ff-ae3f05463eff)
![image](https://github.com/syssi/esphome-jk-bms/assets/5004479/2f7cea01-9bcc-4fe5-962c-ddede79f5473)
![image](https://github.com/syssi/esphome-jk-bms/assets/5004479/67f46e21-8d0e-4f9d-8ffa-b33c57e18cde)
![image](https://github.com/syssi/esphome-jk-bms/assets/5004479/730dd41c-ee6b-4869-9a82-aca0de77f713)
Some of the items are disabled in the list. The other ones are enabled, so you can select from the list but when applying the change using "OK" button a "Sending failure" message can appears. If you reload the screen you can see that the old setting (000 - 4G...) is the active value. 
So:
- 000 - 4G-GPS Remote module.... is selectable & activable (and default)
- 001 - JK BMS 485 Modbus v1.0... is selectable BUT NOT activable
- 002 - NIU U SERIES... is selectable & activable
- 003 - China tower shared battery cabinet... is selectable & activable
- 004 - PACE_RS485_Modbus_v1.3... is NOT selectable because is disabled
- 005 - PYLON_Low_voltage_Protocol_RS4... is NOT selectable because is disabled
- 006 - Growatt_BMS_RS485_Protocol... is selectable & activable
- 007 - Voltronic_inverter_and_BMS_485... is selectable & activable
- 008 - China tower shared battery cabinet... is selectable & activable
- 009 - WOW_RS485_Modbus_V1.3... is selectable & activable
- 010 - Protocol 10... is NOT selectable because is disabled

UART2 Protocol No.: 1 is fixed and has not a list.

CAN Protocol No. has the next list (I have not tested what values are selectable at this moment):
![image](https://github.com/syssi/esphome-jk-bms/assets/5004479/136ff699-a5c5-4c52-a1de-0e72c7cccba5)
![image](https://github.com/syssi/esphome-jk-bms/assets/5004479/2a8211ee-f80b-4221-8b70-0474cb16919f)
![image](https://github.com/syssi/esphome-jk-bms/assets/5004479/8efa42d6-ca82-4e7a-a1aa-b3ee47cf7b43)
![image](https://github.com/syssi/esphome-jk-bms/assets/5004479/bf5be704-ac61-4ce6-8e92-a13d584ca9d8)

**Comment by txubelaxu** [comment]
Hi syssi,

There are 3 lines in the settings menu item (status/**settings**/control) regarding to protocols:
![image](https://github.com/syssi/esphome-jk-bms/assets/5004479/c0e56076-0844-42c4-adbb-3768b73e3377)
UART1 and CAN have "OK" button. UART2 has not. Anyway, "OK" button of UART1 does not work with all values, so any selection cannot be saved at this firmware/app version.

UART1 Protocol No.: has the next list inside:
![image](https://github.com/syssi/esphome-jk-bms/assets/5004479/bd0baa53-8140-451a-82ff-ae3f05463eff)
![image](https://github.com/syssi/esphome-jk-bms/assets/5004479/2f7cea01-9bcc-4fe5-962c-ddede79f5473)
![image](https://github.com/syssi/esphome-jk-bms/assets/5004479/67f46e21-8d0e-4f9d-8ffa-b33c57e18cde)
![image](https://github.com/syssi/esphome-jk-bms/assets/5004479/730dd41c-ee6b-4869-9a82-aca0de77f713)
Some of the items are disabled in the list. The other ones are enabled, so you can select from the list but when applying the change using "OK" button a "Sending failure" message can appears. If you reload the screen you can see that the old setting (000 - 4G...) is the active value. 
So:
- 000 - 4G-GPS Remote module.... is selectable & activable (and default)
- 001 - JK BMS 485 Modbus v1.0... is selectable BUT NOT activable
- 002 - NIU U SERIES... is selectable & activable
- 003 - China tower shared battery cabinet... is selectable & activable
- 004 - PACE_RS485_Modbus_v1.3... is NOT selectable because is disabled
- 005 - PYLON_Low_voltage_Protocol_RS4... is NOT selectable because is disabled
- 006 - Growatt_BMS_RS485_Protocol... is selectable & activable
- 007 - Voltronic_inverter_and_BMS_485... is selectable & activable
- 008 - China tower shared battery cabinet... is selectable & activable
- 009 - WOW_RS485_Modbus_V1.3... is selectable & activable
- 010 - Protocol 10... is NOT selectable because is disabled

UART2 Protocol No.: 1 is fixed and has not a list.

CAN Protocol No. has the next list (I have not tested what values are selectable at this moment):
![image](https://github.com/syssi/esphome-jk-bms/assets/5004479/136ff699-a5c5-4c52-a1de-0e72c7cccba5)
![image](https://github.com/syssi/esphome-jk-bms/assets/5004479/2a8211ee-f80b-4221-8b70-0474cb16919f)
![image](https://github.com/syssi/esphome-jk-bms/assets/5004479/8efa42d6-ca82-4e7a-a1aa-b3ee47cf7b43)
![image](https://github.com/syssi/esphome-jk-bms/assets/5004479/bf5be704-ac61-4ce6-8e92-a13d584ca9d8)

**Comment by txubelaxu** [comment]
See --> https://github.com/txubelaxu/esphome-jk-bms/blob/main/components/jk_rs485_bms/README.md

**Comment by kptkip** [comment]
The given link describes RS485 not RS232 definition

**Comment by gianfrdp** [comment]
I also am interested in RS232.
I tried to connect PC App BMS Monitor w/o success.
Could 00 protocol be same as old JK TTL one?

**Comment by markottenheim** [comment]
I have the same problem, have you found the solution?

**Comment by xiayu6186** [comment]
@txubelaxu 
JK BMS   4G-GPS protocol (id 000) How to switch to JK BMS RS485 Modbus V1.0 (id 001)？？？
4E 57 。。。。。。。？
怎么用指令把000的4G-GPS协议切换到001 modbus协议。。。切换后用modbus协议控制。。。。。
