### ISSUE TITLE
Maybe consider a new version instead of 2.0.0 limiting to 20240601

### ISSUE THREAD

**Issue by bandit7311** [syssi/esphome-jk-bms#513]
Hey there,

right now I have stopped automatic updates to ESPHome as 20240501 caused a lot of issues for me, 
it would be nice if you do new changes and limiting to 20240601 in a new version as probably a lot more people haven´t updated to 20240601 / 20240501,02,03

Could you please explain why 20240601 would be the way to go? 

Thanks a lot 
B

**Comment by syssi** [comment]
The `ota` component requires the `platform` option since ESPHome 2024.6. If you try to compile the updated example YAML including the `platform` option the validation will throw an error on pre 2024.6 releases.

In other words: This component still works with previous ESPHome versions but the examples must be adapted a bit (`platform: esphome` line must be removed).

Do you still suggest a new major release? The breaking chance happened at ESPHome and this project is just affected slightly. ;-)
