### ISSUE TITLE
currently flashing an esp8266 module no longer works.

### ISSUE THREAD

**Issue by duymelody9x** [syssi/esphome-jk-bms#557]
1 month ago i flashed an esp8266 and it worked perfectly, but now flashing a new device it doesn't work anymore. Do you have any updates during this time?
![image](https://github.com/user-attachments/assets/b39ff2fe-febe-4705-83fa-9e85871d1fb7)

**Comment by syssi** [comment]
The implementation haven't changed. Please provide some logs. Do you use another ESP? Did you change the BMS? Please try to identify the changed parts of your setup.

**Comment by duymelody9x** [comment]
i sold the old battery pack i bought a new battery pack and a new 8266 module. But they are the same as the last time i used them. i bought another new 8266 module but it still doesn't work. i'm using batmon addons now i bought an esp32 that connects via bluetooth will they work stably?

**Comment by syssi** [comment]
To resolve the issue it's important to provide more details.

1. Do you have a new BMS too?
2. Are you sure the new BMS has a working GPS port?
3. Is RS485 enabled and the correct protocol selected?
4. Does Batman use a wired connection or BLE?
5. Which GPIOs did you use for RXD and TXD? Please provide your YAML configuration
6. Enable the `debug` output of the `uart` component and provide some logs

**Comment by syssi** [comment]
Some ideas:

1. There are D1 mini boards out there where GPIO1/GPIO3 cannot talk to the BMS because the UART-to-TTL chip attached to the same pins makes strange things. Please try GPIO4, GPIO5 instead.
2. May be the underlying Arduino implementation has changed. I'm using ESP32 boards only without trouble. Please try an ESP32 just for testing.
3. If the GPS port remains silent you have to use BLE unfortunately.

**Comment by duymelody9x** [comment]
Which ESP32 boards do you usually use?

**Comment by syssi** [comment]
They are called `ESP32 D1 Mini` and are looking very similar to the Wemos D1 Mini board. Be careful to not pick a ESP8266 based board. ;-)
